from .string_property import StringPropertyTests
from .mapper import MapperTests
from .list_property import ListPropertyTests
from .result import MapResultTests
from .compound_property import CompoundPropertyTests
from .property_ref import PropertyRefTests
from .dict_property import DictPropertyTests
from .integer_property import IntegerPropertyTests
from .float_property import FloatPropertyTests
from .boolean_property import BooleanPropertyTests
from .property import PropertyTests
from .examples import ExamplesTests
